### ISSUE TITLE
Map does no refresh when the pin has been deleted

### ISSUE THREAD

**Issue by zmartl** [zperee/AppQuest_Schatzkarte#1]
When click on a pin and confirm the following alert, the pin will be removed from the list but it's still visible in the map.

**Comment by zmartl** [comment]
Fixed it! :tada:
You have to add the following lines after you removed the pin from map.Pins. 
await PrepareListForLocalFileAsync();
_map.Pins.Clear();
await FillPinsAsync();

**Comment by zperee** [comment]
The marker is now removed with Pins.Clear(). This is not the best solution, but for now it should work.
